# Generated by Django 3.2.11 on 2022-06-07 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='updated_on')),
                ('deleted_on', models.DateTimeField(db_column='deleted_on', default=None, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected'), (3, 'Under review'), (4, 'Marked Spam')], default=3)),
                ('content_type', models.IntegerField(choices=[(1, 'Chat'), (2, 'Chat History'), (3, 'Feed Post'), (4, 'Comment')], default=3, help_text='Integer denoting the `content_type` of the objectAvailable choices are `ContentTypeChoices.choices`')),
                ('text', models.TextField(blank=True, help_text='All the textual data of the post. May contain links as well')),
                ('parent', models.ForeignKey(help_text='ForeignKey relationship to an object of the same classUsed to implement parent-child relationsips. Eg- Post and its comments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content_app.content')),
                ('user', models.ForeignKey(help_text='Foreign Key to the `YearbookGamingUser` who created the content', on_delete=django.db.models.deletion.CASCADE, related_name='created_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'get_latest_by': 'updated_on',
            },
        ),
        migrations.CreateModel(
            name='UploadObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='updated_on')),
                ('deleted_on', models.DateTimeField(db_column='deleted_on', default=None, null=True)),
                ('s3_object_key', models.CharField(help_text='The unique key that identifies the media on S3', max_length=500, unique=True)),
                ('extension', models.CharField(default='jpeg', help_text='Extension of the file to be uploaded', max_length=8)),
                ('meta', models.JSONField(default=dict, help_text='JSON Object containing meta-data of the fileUsed only for reading, not for querying')),
                ('upload_complete', models.BooleanField(default=False, help_text='Boolean denoting if the file has been successfully uploaded')),
                ('content', models.ForeignKey(help_text='ForeignKey Relationship field with `content_app.Content`Denotes the `content` object associated with the instance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='content_app.content')),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'get_latest_by': 'updated_on',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='updated_on')),
                ('deleted_on', models.DateTimeField(db_column='deleted_on', default=None, null=True)),
                ('reaction', models.IntegerField(choices=[(1, 'LIKE'), (2, 'LOVE'), (3, 'LAUGH'), (4, 'HUG'), (5, 'WOW'), (6, 'SAD'), (7, 'ANGRY'), (8, 'CRY'), (9, 'SMIRK'), (10, 'PLEAD'), (11, 'SWAG'), (12, 'SHIT')], default=1)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='content_app.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'get_latest_by': 'updated_on',
                'abstract': False,
            },
        ),
    ]
