# Generated by Django 3.2.11 on 2022-06-04 12:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='YearbookGamingmoderator',
            name='last_logout',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 12, 37, 23, 590343, tzinfo=utc), help_text='Last logout date-time of the moderator'),
        ),
        migrations.CreateModel(
            name='TicketBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on', help_text='DateTime of when the object was created')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='updated_on', help_text='DateTime of when the object was last updated')),
                ('deleted_on', models.DateTimeField(default=None, help_text='DateTime of when the object was deletedNone if object is not deleted yet', null=True)),
                ('escalated', models.IntegerField(default=0)),
                ('rejected', models.IntegerField(default=0)),
                ('accepted', models.IntegerField(default=0)),
                ('user', models.OneToOneField(help_text='Foreign key to `YearbookGamingUser` used to authenticate this moderator', on_delete=django.db.models.deletion.CASCADE, related_name='board', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'get_latest_by': 'updated_on',
                'abstract': False,
            },
        ),
    ]
