# Generated by Django 3.2.11 on 2022-06-04 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0003_alter_YearbookGamingmoderator_last_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Approved'), (2, 'Rejected'), (3, 'Under review'), (4, 'Marked Spam'), (5, 'Escalated')], default=3, help_text='Status of any object in the database in the context of moderation'),
        ),
        migrations.AlterField(
            model_name='YearbookGamingmoderator',
            name='last_logout',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 12, 40, 0, 786650, tzinfo=utc), help_text='Last logout date-time of the moderator'),
        ),
    ]
