# Generated by Django 3.2.11 on 2022-06-04 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0004_auto_20220604_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='YearbookGamingmoderator',
            name='last_logout',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 12, 40, 6, 755109, tzinfo=utc), help_text='Last logout date-time of the moderator'),
        ),
    ]
