# Generated by Django 3.2.11 on 2022-06-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0005_alter_Yearbookmoderator_last_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Yearbookmoderator',
            name='last_logout',
            field=models.DateTimeField(help_text='Last logout date-time of the moderator'),
        ),
    ]
