# Generated by Django 3.2.11 on 2022-06-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0006_alter_YearbookGamingmoderator_last_logout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketboard',
            old_name='accepted',
            new_name='approved',
        ),
    ]
