# Generated by Django 3.2.11 on 2022-06-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0007_rename_accepted_ticketboard_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketboard',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
