# Generated by Django 3.2.11 on 2022-06-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0008_ticketboard_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='YearbookGamingmoderator',
            name='average_response_time',
        ),
        migrations.RemoveField(
            model_name='YearbookGamingmoderator',
            name='posts_abandoned',
        ),
        migrations.RemoveField(
            model_name='YearbookGamingmoderator',
            name='times_abandoned',
        ),
        migrations.RemoveField(
            model_name='YearbookGamingmoderator',
            name='total_logged_in_time',
        ),
        migrations.RemoveField(
            model_name='YearbookGamingmoderator',
            name='user_rating',
        ),
        migrations.AddField(
            model_name='ticketboard',
            name='average_response_time',
            field=models.BigIntegerField(default=10, help_text='Average response time of the moderator. Defaults to 10'),
        ),
        migrations.AddField(
            model_name='ticketboard',
            name='posts_abandoned',
            field=models.IntegerField(default=0, help_text='Number of posts that had to be re-queued because this moderator abandoned'),
        ),
        migrations.AddField(
            model_name='ticketboard',
            name='times_abandoned',
            field=models.IntegerField(default=0, help_text='Number of times this moderator has abandoned the systemAbandoned by sitting idle and not log-outing'),
        ),
        migrations.AddField(
            model_name='ticketboard',
            name='total_logged_in_time',
            field=models.IntegerField(default=0, help_text='Total time in minutes for which the moderator was logged in the system'),
        ),
    ]
