# Generated by Django 3.2.11 on 2022-06-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0009_auto_20220604_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketboard',
            name='average_response_time',
            field=models.BigIntegerField(default=-1, help_text='Average response time of the moderator. Defaults to 10'),
        ),
    ]
