# Generated by Django 3.2.11 on 2022-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0010_alter_ticketboard_average_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketboard',
            name='average_response_time',
            field=models.BigIntegerField(default=10, help_text='Average response time of the moderator in seconds. Defaults to 10'),
        ),
    ]
