# Generated by Django 3.2.11 on 2022-06-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0011_alter_ticketboard_average_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationticket',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Approved'), (2, 'Rejected'), (3, 'Under review'), (4, 'Marked Spam'), (5, 'Escalated')], default=3, help_text='Status of any object in the database in the context of moderation'),
        ),
    ]
