#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

python manage.py makemigrations
python manage.py migrate
python manage.py runserver 0.0.0.0:8000
# gunicorn docker_django.wsgi:application — bind 0.0.0.0:8000